version: '3.1'


services:
  backend:
    image: rostiislav/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/static
      - media:/backend/media
    depends_on:
      - db
  db:
    image: postgres:13
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgres/data

  frontend:
    env_file: .env
    image: rostiislav/kittygram_frontend:latest
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: rostiislav/kittygram_gateway:latest
    env_file: .env
    ports:
      - "9000:80"
    volumes:
      - static:/static
      - media:/backend/media

    depends_on:
      - backend

volumes:
  pg_data:
  static:
  media:
